name: dmg angular pwa deploy

on:
  push:
    branches:
      - master
    paths: #hangi dosyalarda değişiklik olursa action çalışacak?
      - ".github/workflows/deploy.yml"
      - "src/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ng build
      - name: Archive Artifact
        uses: actions/upload-artifact@master
        with:
          name: dmg-angular-pwa #zip file name
          path: dist/angular-pwa #ziplenecek folder

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dmg-angular-pwa #zip file name
          path: dist/angular-pwa #çıkarılacak path
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dmg-angular-pwa-deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "dmg-angular-pwa"
